demoinstance:
    build: .
    volumes:
        - ./backend/demoinstance/:/opt/demoinstance/backend/demoinstance/
        - ./frontend/:/opt/demoinstance/frontend/
        - ./config/:/etc/demoinstance/
        - ./ressources/supervisor_dev:/etc/supervisor/conf.d
        - ./ressources/dev_demoinstance:/opt/demoinstance/dev_demoinstance
        - ./ressources/dev_demoinstance.py:/opt/demoinstance/dev_demoinstance.py
    ports:
        - "8080:8080"
    expose:
        - "8080"
    links:
      - mysql
mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=demo



