#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


function finish {
    echo "Fixing file permissions: it might take some time"
    if [ -d "/opt/demoinstance/backend/demoinstance" ]; then
	cd /opt/demoinstance/backend/demoinstance
	chown -R `stat -c "%u:%g" .` .
    fi
}


trap finish EXIT


python2 /opt/demoinstance/dev_demoinstance.py $@